import './globals.css'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import "react-toastify/ReactToastify.min.css"
import AuthProvider from '@/components/AuthProvider'
import Protected from '@/components/Protected'
import NextTopLoader from 'nextjs-toploader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Home | Acropolis FCA',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
  <html lang="en">
    <body className={inter.className}>
      <ToastContainer />
      <NextTopLoader color="#1d4ed8" showSpinner={false} />
      <AuthProvider>
        <Protected>
          <ToastContainer />
          {children}
        </Protected>
      </AuthProvider>
    </body>
  </html>
  )
}
